baseurl = "https://angelabad.me/cv"
title = "Angel Abad"
author = "Angel Abad"
copyright = "Copyright © 2019, Angel Abad; all rights reserved."
canonifyurls = true
paginate = 3

theme = "winning"
publishDir = "../docs/cv"

googleAnalytics = "UA-133867173-1"

[markup.goldmark.renderer]
unsafe= true
