baseURL = "https://example.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "John Doe · Landing Page"

[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Angel Abad"
description = "Landing Page"
bio = "Devops / Systems Engineer.<br/>Debian Developer<br/>Ubuntu MOTU Developer."
avatar = "img/angel1.png"
favicon = "img/favicon.ico"

	[params.contact]
    email = "angelabad@gmail.com"
    debian = "angel"
    ubuntu = "angelabad"
    gitlab = "angelabad"
    github = ""
    instagram = ""
    twitter = "angelabad"
    ello = ""
    

