baseURL = "https://angelabad.me/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt"
title = "Angel Abad · Page"

[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Angel Abad"
description = "resume of an experienced, professional devops / systemes engineer looking for work."
keywords = "resume, aws, devops, terraform, packer, ansible, ec2, kubernetes, docker, monitoring, golang, ec2, auto-scaling, apache, nginx"
bio = "Devops / Systems Engineer.<br/>Debian Developer<br/>Ubuntu MOTU Developer.<br/><a href=\"https://angelabad.me/cv\">CV/Resume</a>"
avatar = "img/angel.png"
favicon = "img/favicon.ico"

	[params.contact]
    email = "angelabad@gmail.com"
    debian = "angel"
    ubuntu = "angelabad"
    gitlab = "angelabad"
    linkedin = "angelabad"
    github = "angelabad"
    instagram = ""
    twitter = "angelabad"
    ello = ""
    

